version: '2.4'
services:
    #Duplicate this section for each repeater
    #do docker-compose down and then docker-compose up -d in this 
    #directory afterwards to stop and start the containers 
    #you may need to do conntrack -F after the restart
    RYSEN-Hytera:
        container_name: RYSEN-Hytera
        ports:
            - '50000:50000/udp'
            - '50001:50001/udp'
            - '50002:50002/udp'
        environment:
          #Configure Repeater server side (DMRGateway)
          #Put an Options line here to configure static TGs etc
          - 'DMRG_OPTIONS=TS1=23590;DIAL=2350;VOICE=1;LANG=en_GB;SINGLE=1;TIMER=10;'
            #If not empty, rewrite TS1TG9 to the TG specified
          - 'DMRG_REWRITETS1TG9='
          #Target server
          - DMRG_TARGET=
          # callsign and repeater_dmr_id, if provided will override the one read from repeater
          - callsign=
          - repeater_dmr_id=
          # params for configuration reporting
          - color_code=
          - latitude=
          - longitude=
          - antenna_height=
          # 20 ascii letters, will be trimmed if exceeded
          - location=
          - description=
          # use these to override params read out of repeater
          - rx_freq=
          - tx_freq=
          - tx_power=
          # 1 = only TS1, 2 = only TS2, 3 = TS1 and TS2
          - timeslots=3

        image: 'RYSEN-HYT:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        networks:
           - app_net
      
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
